# Generated by Django 3.0.2 on 2020-11-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotorControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_id', models.IntegerField()),
                ('motor_pos', models.IntegerField()),
            ],
        ),
    ]
